var timeOuts=new Array();var receiveMesReq=getXmlHttpRequestObject();function getMessages(){if(receiveMesReq.readyState==4||receiveMesReq.readyState==0){receiveMesReq.open("GET",'includes/messageData.php?roomID='+room+'&last='+messageID,true);receiveMesReq.onreadystatechange=handleMessages;receiveMesReq.send(null);}}
function handleMessages(){if(receiveMesReq.readyState==4){var xmldoc=receiveMesReq.responseXML;var allUsers_nodes=xmldoc.getElementsByTagName("usermessage");var n_users=allUsers_nodes.length;for(i=0;i<n_users;i++){var uID_node=allUsers_nodes[i].getElementsByTagName("uid");var uAction_node=allUsers_nodes[i].getElementsByTagName("uaction");var uRefid_node=allUsers_nodes[i].getElementsByTagName("urefid");var uUserid_node=allUsers_nodes[i].getElementsByTagName("userid");var uName_node=allUsers_nodes[i].getElementsByTagName("uname");var uToname_node=allUsers_nodes[i].getElementsByTagName("utoname");var uRoom_node=allUsers_nodes[i].getElementsByTagName("uroom");var uMessage_node=allUsers_nodes[i].getElementsByTagName("umessage");var uAvatar_node=allUsers_nodes[i].getElementsByTagName("uavatar");var uAvatarX_node=allUsers_nodes[i].getElementsByTagName("uavatarx");var uAvatarY_node=allUsers_nodes[i].getElementsByTagName("uavatary");var uTime_node=allUsers_nodes[i].getElementsByTagName("utime");showMessages(uAction_node[0].firstChild.nodeValue,uID_node[0].firstChild.nodeValue,uName_node[0].firstChild.nodeValue,uToname_node[0].firstChild.nodeValue,uMessage_node[0].firstChild.nodeValue,uRefid_node[0].firstChild.nodeValue,uAvatarX_node[0].firstChild.nodeValue,uAvatarY_node[0].firstChild.nodeValue);}
mTimer=setTimeout('getMessages();',refreshMessages);mTimer=0;}}
var divID='0';var divPID='0';var divCPID='0';var doPublicChat=1;function showMessages(dAction,dID,dName,dToname,dMessage,dRefid,dX,dY){dMessage=unescape(dMessage);dMessage=dMessage.replace(/&amp;#39;/g,"&#39;");dMessage=dMessage.replace(/&amp;#60;/g,"&#60;");dMessage=dMessage.replace(/&amp;#62;/g,"&#62;");dMessage=dMessage.replace(/&amp;#39;/g,"&#39;");dMessage=dMessage.replace(/&amp;#34;/g,"&#34;");dMessage=dMessage.replace(/&amp;#37;/g,"&#37;");if(dAction=='reqfriend'&&dToname.toLowerCase()==chatName.toLowerCase()){addFriendOptions(dID,dName);return false;}
if(dAction=='accfriend'&&dToname.toLowerCase()==chatName.toLowerCase()){accFriendReq(dID,dName);return false;}
if(dAction=='kick'&&dToname.toLowerCase()==chatName.toLowerCase()){loadRoom(kickRoom);return false;}
if(dAction=='ban'&&dToname.toLowerCase()==chatName.toLowerCase()){window.location="?do=logout&action=banned";return false;}
var isThisUser='0';if(dName.toLowerCase()==chatName.toLowerCase()){isThisUser='1';}
var systemMess;if(dAction=='logout'){hideUsers('_'+dRefid+'_');}
messageID=dID;var showToname='';if(dToname!='-'){showToname="";}
if(dAction=='love'||dAction=='like'||dAction=='star'){dMessage=dMessage.replace(/heart.png/gi,"<img src='images/heart.png'>");dMessage=dMessage.replace(/thumbs_up.png/gi,"<img src='images/thumbs_up.png'>");dMessage=dMessage.replace(/star.png/gi,"<img src='images/star.png'>");updateUserPoints();}else{systemMess=dName;dMessage=addSmilies(dMessage);}
if((systemMess=='SYSTEM')||dAction=='block'||dAction=='unblock'||dAction=='interaction'){dName='(Bilgi)';}
divID=Number(divID)+ 1;if((dToname!='-'&&systemMess!='SYSTEM')||(systemMess=='SYSTEM'&&dAction=='logout')){divPID=Number(divPID)+ 1;var pwdRefid=dRefid.replace(/_/gi,"");if(chatName.toLowerCase()!=dToname.toLowerCase()){divCPID="_"+chatName.toLowerCase()+dToname.toLowerCase()+"_";var tgName=dToname;}else{divCPID="_"+chatName.toLowerCase()+dName.toLowerCase()+"_";var tgName=dName;}
if(!document.getElementById("tg"+divCPID)&&dAction=='logout'){doPublicChat();return false;}
createPChatWindow(divCPID,tgName);var ni=document.getElementById(divCPID);var newdiv=document.createElement('div');newdiv.setAttribute("id",divPID);newdiv.className='';var doFont='black';if(dAction=='logout'){doFont=_fontLogout;}
if(dAction=='login'){doFont=_fontLogin;}
if(dName.toLowerCase()==chatName.toLowerCase()){doFont=_fontSelf;}
if(dAction=='love'||dAction=='like'||dAction=='star'||dAction=='logout'||dAction=='login'){newdiv.innerHTML="<font color='"+doFont+"'>(Bilgi):&nbsp;"+ showToname+ dMessage+"</font>";}else{newdiv.innerHTML="<font color='"+doFont+"'>"+dName+":&nbsp;"+ showToname+ dMessage+"</font>";}
ni.appendChild(newdiv);ni.scrollTop=ni.scrollHeight;if(divPID>_maxMessages){divMessagePID=divPID- _maxMessages;if(document.getElementById(divMessagePID)){var dm=document.getElementById(divCPID);var olddiv=document.getElementById(divMessagePID);dm.removeChild(olddiv);}}
if(document.getElementById(divCPID).style.visibility!='visible'){document.getElementById("tg"+divCPID).style.backgroundColor="#ff9900";}}
if(dToname=='-'||dAction=='login'&&systemMess=='SYSTEM'&&dToname.toLowerCase()==chatName.toLowerCase()){doPublicChat();}
function doPublicChat(){if(dAction=='love'||dAction=='like'||dAction=='star'){return false;}
var ni=document.getElementById('chatbox');var newdiv=document.createElement('div');newdiv.setAttribute("id",divID);newdiv.className='';var doFont='black';if(dAction=='logout'){doFont=_fontLogout;}
if(dAction=='login'){doFont=_fontLogin;dMessage=dMessage.replace(/&#60;/,"<");dMessage=dMessage.replace(/&#62;/,">");}
if(dAction=='interaction'){doFont=_fontIAction;}
if(dName.toLowerCase()==chatName.toLowerCase()){doFont=_fontSelf;}
newdiv.innerHTML="<font color='"+doFont+"'>"+dName+":&nbsp;"+ showToname+ dMessage+"</font>";ni.appendChild(newdiv);ni.scrollTop=ni.scrollHeight;if(divID>_maxMessages){divMessageID=divID- _maxMessages;if(document.getElementById(divMessageID)){var dm=document.getElementById('chatbox');var olddiv=document.getElementById(divMessageID);dm.removeChild(olddiv);}}
if(document.getElementById("chatbox").style.visibility!='visible'&&dName.toLowerCase()!=chatName.toLowerCase()){document.getElementById("tgchatbox").style.backgroundColor="#FFE4A9";}}
if(document.getElementById('_'+dRefid+'_myMessage')){if(systemMess!='SYSTEM'||dMessage!=''){document.getElementById('_'+dRefid+'_myMessage').innerHTML=dMessage;var _x=document.getElementById('_'+dRefid+'_myAvatar').offsetLeft;var _y=document.getElementById('_'+dRefid+'_myAvatar').offsetTop;var _posShowX=20;var _posShowXX=15;if(_x>400){_posShowX=20- document.getElementById('_'+dRefid+"_myMessage").clientWidth;document.getElementById('_'+dRefid+"_myMessage").style.paddingLeft="10px";document.getElementById('_'+dRefid+"_myMessage").style.paddingRight="0px";var _doRe=1;_posShowXX=5;}else{document.getElementById('_'+dRefid+"_myMessage").style.paddingLeft="0px";document.getElementById('_'+dRefid+"_myMessage").style.paddingRight="10px";var _doRe=0;}
document.getElementById('_'+dRefid+"_myMessage").style.paddingTop="11px";_yy=_y- 50;_xx=_x+ _posShowX;document.getElementById('_'+dRefid+'_myMessage').style.left=_xx+'px';document.getElementById('_'+dRefid+'_myMessage').style.top=_yy+'px';document.getElementById('_'+dRefid+'_myMessage').style.height='30px';document.getElementById('_'+dRefid+'_myMessage').style.background="url(images/sp2.png)";_yyy=_y- 50;_xxx=_xx- _posShowXX;document.getElementById('l_'+dRefid+'_myMessage').style.left=_xxx+'px';document.getElementById('l_'+dRefid+'_myMessage').style.top=_yyy+'px';if(_doRe==0){document.getElementById('l_'+dRefid+'_myMessage').style.height='48px';document.getElementById('l_'+dRefid+'_myMessage').style.width='16px';document.getElementById('l_'+dRefid+'_myMessage').style.background="url(images/sp1.png)";}else{document.getElementById('l_'+dRefid+'_myMessage').style.height='43px';document.getElementById('l_'+dRefid+'_myMessage').style.width='9px';document.getElementById('l_'+dRefid+'_myMessage').style.background="url(images/sp3rev.png)";}
setRightSpeech=document.getElementById('_'+dRefid+'_myMessage').clientWidth;_yyyy=_y- 50;_xxxx=_xx+ setRightSpeech;document.getElementById('r_'+dRefid+'_myMessage').style.left=_xxxx+'px';document.getElementById('r_'+dRefid+'_myMessage').style.top=_yyyy+'px';if(_doRe==0){document.getElementById('r_'+dRefid+'_myMessage').style.height='43px';document.getElementById('r_'+dRefid+'_myMessage').style.width='9px';document.getElementById('r_'+dRefid+'_myMessage').style.background="url(images/sp3.png)";}else{document.getElementById('r_'+dRefid+'_myMessage').style.height='48px';document.getElementById('r_'+dRefid+'_myMessage').style.width='16px';document.getElementById('r_'+dRefid+'_myMessage').style.background="url(images/sp1rev.png)";}
document.getElementById('_'+dRefid+'_myMessage').style.visibility='visible';document.getElementById('l_'+dRefid+'_myMessage').style.visibility='visible';document.getElementById('r_'+dRefid+'_myMessage').style.visibility='visible';dMessage='';}}
clearTimeout(timeOuts[dRefid]);timeOuts[dRefid]=setTimeout('hideUsersSpeech("'+dRefid+'")',showUserChat);}
function hideUsersSpeech(dRefid){if(document.getElementById('_'+dRefid+'_myMessage')&&document.getElementById('_'+dRefid+'_myMessage').style.visibility!='hidden'){document.getElementById('_'+dRefid+'_myMessage').style.visibility='hidden';document.getElementById('l_'+dRefid+'_myMessage').style.visibility='hidden';document.getElementById('r_'+dRefid+'_myMessage').style.visibility='hidden';}}
function createChatTabs(divCPID,tgName){if(!document.getElementById("tg"+divCPID)){var nt=document.getElementById('chattab');var tg=document.createElement('span');tg.id="tg"+divCPID;tg.className="privatetab";if(divCPID=='chatbox'){tg.innerHTML="<span onClick=activeChatWindow();showChatWindow('"+divCPID+"','"+tgName+"');>Konusma Gecmisi</span>&nbsp;";}else{tg.innerHTML="<span onClick=activeChatWindow();showChatWindow('"+divCPID+"','"+tgName+"');>"+ tgName.substring(0,7)+"...</span>";tg.innerHTML+="<span onClick=delChatWindow('"+divCPID+"')>[x]</span>&nbsp;";}
nt.appendChild(tg);}
textOptions(divCPID);}
function textOptions(divCPID){document.getElementById('chatoptions').innerHTML="<span style='cursor:pointer;padding-bottom:2px;' onClick=decreaseFontSize('"+divCPID+"'); alt='Yazilari kucult' title='Yazilari kucult'><img src='images/textoptions/decT.png' border='0'></span>";document.getElementById('chatoptions').innerHTML+="<span style='cursor:pointer;padding-bottom:2px;' onClick=increaseFontSize('"+divCPID+"'); alt='Yazilari buyut' title='Yazilari buyut'><img src='images/textoptions/incT.png' border='0'></span>";document.getElementById('chatoptions').innerHTML+="<span style='cursor:pointer;padding-bottom:2px;' onClick=toggleBox('"+divCPID+"');hidetextOptions(); alt='Konusma gecmisini gizle' title='Konusma gecmisini gizle'><img src='images/textoptions/minT.png' border='0'></span>";document.getElementById('chatoptions').innerHTML+="<span style='cursor:pointer;padding-bottom:2px;' onClick=reduceScreen('"+divCPID+"'); alt='Kucuk ekran' title='Kucuk ekran'><img src='images/textoptions/medT.png' border='0'></span>";document.getElementById('chatoptions').innerHTML+="<span style='cursor:pointer;padding-bottom:2px;' onClick=enlargeScreen('"+divCPID+"'); alt='Buyuk ekran' title='Buyuk ekran'><img src='images/textoptions/maxT.png' border='0'></span>";}
var isWindowSize=0;function enlargeScreen(divCPID){document.getElementById(divCPID).style.height='400px';document.getElementById(divCPID).style.width='600px';document.getElementById('chatoptions').style.top='53px';document.getElementById('chatoptions').style.width='604px';if(ie7)
{document.getElementById('chatoptions').style.top='100px';document.getElementById('chatoptions').style.width='600px';}
document.getElementById('chatoptions').style.left='5px';textOptions(divCPID);isWindowSize=1;moveAvatar='0';}
function reduceScreen(divCPID){document.getElementById(divCPID).style.height='150px';document.getElementById(divCPID).style.width='300px';document.getElementById('chatoptions').style.top='299px';document.getElementById('chatoptions').style.width='304px';if(ie7)
{document.getElementById('chatoptions').style.top='350px';document.getElementById('chatoptions').style.width='300px';}
document.getElementById('chatoptions').style.left='5px';document.getElementById('chatoptions').style.visibility='visible';textOptions(divCPID);isWindowSize=0;moveAvatar='0';}
function hidetextOptions(){document.getElementById('chatoptions').style.visibility='hidden';moveAvatar='0';}
function createPChatWindow(divCPID,tgName){if(!document.getElementById(divCPID)){var divTag=document.createElement("div");divTag.id=divCPID;divTag.className="chatbox";document.body.appendChild(divTag);createChatTabs(divCPID,tgName);}}
var showThis='chatbox';function showChatWindow(activeChat,tgName){showThis=activeChat;toWhisper=tgName;document.getElementById(activeChat).style.visibility='visible';document.getElementById('chatoptions').style.visibility='visible';document.getElementById("tg"+activeChat).style.background="url(images/chatboxbg.png) repeat-x";textOptions(activeChat);if(isWindowSize==1){enlargeScreen(activeChat);}else{reduceScreen(activeChat);}}
function activeChatWindow(){if(document.getElementById(showThis)){document.getElementById(showThis).style.visibility='hidden';}}
function delChatWindow(delChat){if(document.getElementById(delChat)&&document.getElementById(delChat)!=document.getElementById('chatbox')){var d=document.getElementById('body');var olddiv=document.getElementById(delChat);d.removeChild(olddiv);document.getElementById('chatoptions').style.visibility='hidden';toWhisper='';}
if(document.getElementById("tg"+delChat)&&document.getElementById("tg"+delChat)!=document.getElementById('tgchatbox')){var d=document.getElementById('chattab');var olddiv=document.getElementById("tg"+delChat);d.removeChild(olddiv);}}
var min=8;var max=18;function increaseFontSize(divCPID){var p=document.getElementById(divCPID).style.fontSize;p=p.replace("px","");if(!p){p=parseInt(12);}
if(parseInt(p)!=parseInt(max)){p=parseInt(p)+ parseInt('1');}
document.getElementById(divCPID).style.fontSize=p+"px";moveAvatar='0';}
function decreaseFontSize(divCPID){var p=document.getElementById(divCPID).style.fontSize;p=p.replace("px","");if(!p){p=parseInt(12);}
if(parseInt(p)!=parseInt(max)){p=parseInt(p)- parseInt('1');}
document.getElementById(divCPID).style.fontSize=p+"px";moveAvatar='0';}